"""add relationship

Revision ID: f189d1b2c29f
Revises: 5adad5917b9c
Create Date: 2026-08-07 17:58:24.324085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f189d1b2c29f'
down_revision: Union[str, Sequence[str], None] = '5adad5917b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraries', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Backlog'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'status')
    # ### end Alembic commands ###
